[Misc] Removed undefined cmake variables MOE_PERMUTE_ARCHS
Looks like this was missed from https://github.com/vllm-project/vllm/pull/14568

It caused issues when we build vllm with TORCH_CUDA_ARCH_LIST being specified
such as TORCH_CUDA_ARCH_LIST="9.0a". Because we didn't pass CUDA_ARCHS correctly
to compile moe_permute_unpermute_op, we ended up with the following failure:

Without the fix:
```
$ pytest tests/kernels/moe/test_cutlass_moe.py -k test_run_cutlass_moe_fp8[8-True-False-128-1-8192-5120-31]
...
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain
```

With the fix:
```
$ pytest tests/kernels/moe/test_cutlass_moe.py -k test_run_cutlass_moe_fp8[8-True-False-128-1-8192-5120-31]
...
1 passed, 461 deselected, 2 warnings in 5.00s
```

Tags:
Signed-off-by: Yang Chen <yangche@fb.com>